#!/usr/bin/env python3

#!Python
#Usage:
#bedGraphTobed in.bedGraph out.bed MapQualCff
#DRT stands for DNA replicating timing
#option:
#For debug use only
#command='bedGraphTobed hg38.50mer.bedGraph hg38.50mer.bed 0.2'
#sys.argv=command.split()
import os
import sys
if not len(sys.argv)==4:
   print('usage:bedGraphTobed in.bedGraph out.bed MapQualCff')
else:
   filein=sys.argv[1]
   fileout=sys.argv[2]
   cutoff=float(sys.argv[3])
   fin=open(filein)
   fo=open(fileout,'w')
   for line in fin:
      pin=line.strip().split()
      if float(pin[-1])>cutoff:
         print(' '.join(pin[:3]), file=fo)
   fin.close()
   fo.close()

